### ISSUE TITLE
Module not found: Error: Can't resolve 'react-leaflet-waypoints'

### ISSUE THREAD

**Issue by p-butovets** [ozaytsev86/react-leaflet-waypoints#11]
https://prnt.sc/1KDiFkGHipoF

**Comment by ozaytsev86** [comment]
Hi @p-butovets , thanks for your interest. It was long time without doing anything in this project. Im taking a look at it right now, will give you a better answer on the weekend as I will have more time to work on it. Meanwhile I suggest you to try the version 0.1.7 as it was the last one I tried in the test project https://github.com/ozaytsev86/react-leaflet-waypoints-test. Let me know if you need a hand with it.

**Comment by ozaytsev86** [comment]
I've fixed it in the v0.1.15. Cheers.
